name: add_2_calendar
description: A really simple Flutter plugin to add events to each platform's default calendar.
version: 1.4.1
homepage: https://github.com/ja2375/add_2_calendar

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.javih.add2calendar
        pluginClass: Add2CalendarPlugin
      ios:
        pluginClass: SwiftAdd2CalendarPlugin
